In [1]:
import torch
print(torch.__version__)

2.7.0+cu118


# All about tensors

### Basics

In [2]:
scaler=torch.tensor(7)
scaler                           

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
vector = torch.tensor([7,7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
matrix = torch.tensor([[1,2],[2,3]])
matrix

tensor([[1, 2],
        [2, 3]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
tensor = torch.tensor([[[1,2,3],
                        [2,3,4],
                        [3,4,5]]])
tensor

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust the random numbers to better understand the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [11]:
Rand_T = torch.rand(1,3,4)
Rand_T

tensor([[[0.2172, 0.7452, 0.0540, 0.3809],
         [0.3018, 0.1216, 0.7671, 0.7394],
         [0.1045, 0.1662, 0.1999, 0.9585]]])

In [12]:
# Random tensor similar to already existing tensor
Rand_T_similair_to_already_existing_tensor = torch.rand_like(Rand_T)
Rand_T_similair_to_already_existing_tensor

tensor([[[0.4820, 0.0627, 0.5514, 0.5028],
         [0.9018, 0.4841, 0.9040, 0.0599],
         [0.3531, 0.2318, 0.8157, 0.6357]]])

In [13]:
# Random tensor with similar shape to an image tensor
image_t = torch.rand(size=(224,224,3))
image_t

tensor([[[0.8850, 0.8372, 0.8364],
         [0.2509, 0.6372, 0.1444],
         [0.3723, 0.8682, 0.7958],
         ...,
         [0.2503, 0.4323, 0.4617],
         [0.8633, 0.6826, 0.3854],
         [0.2899, 0.1663, 0.6483]],

        [[0.2338, 0.6567, 0.6716],
         [0.4214, 0.7832, 0.9846],
         [0.7025, 0.0446, 0.4048],
         ...,
         [0.7856, 0.7314, 0.5844],
         [0.7564, 0.2756, 0.8467],
         [0.0869, 0.1366, 0.7361]],

        [[0.0043, 0.5628, 0.8224],
         [0.9700, 0.6432, 0.9264],
         [0.4694, 0.9841, 0.2929],
         ...,
         [0.2981, 0.4434, 0.1448],
         [0.3651, 0.3632, 0.1721],
         [0.1246, 0.7509, 0.6108]],

        ...,

        [[0.8084, 0.3404, 0.1957],
         [0.6711, 0.4855, 0.9708],
         [0.2785, 0.7647, 0.4968],
         ...,
         [0.6523, 0.5329, 0.6665],
         [0.3910, 0.9708, 0.9489],
         [0.7571, 0.6403, 0.0857]],

        [[0.0241, 0.7981, 0.9838],
         [0.5076, 0.5473, 0.1494],
         [0.

### Zeros and ones

In [14]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensor like

In [16]:
range_t = torch.arange(1,20)
range_t

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [17]:
# Creating a tensor like
zer = torch.zeros_like(range_t)
zer

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Errors that can occur with tensors:

1. Tensors not right datatype
2. not right shape
3. not on the right device

In [18]:
# float 32
float_32_t = torch.tensor([3.0,4.0,3.3],
                          dtype=None, # Defines the datatype for the tensor
                          device=None, # Mentions the device where the tensor is stored
                          requires_grad=False, # To track the gradients of the tensor
                          )

float_32_t

tensor([3.0000, 4.0000, 3.3000])

In [19]:
float_16_t = float_32_t.type(torch.HalfTensor)
float_16_t

tensor([3.0000, 4.0000, 3.3008], dtype=torch.float16)

In [20]:
float_32_t * float_16_t

tensor([ 9.0000, 16.0000, 10.8926])

### Getting information from tensors (Tensor attributes)
1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

In [21]:
F= torch.rand(3,4)
F

tensor([[0.5313, 0.7174, 0.6426, 0.7842],
        [0.1918, 0.9846, 0.0258, 0.1916],
        [0.3670, 0.2775, 0.1461, 0.5175]])

In [22]:
#finding specific informations abt the tensor

print("datatype = ",F.dtype)
print("Shape: ",F.shape)
print("Device: " ,F.device)

datatype =  torch.float32
Shape:  torch.Size([3, 4])
Device:  cpu


### Manipulatin Tensors (tensor operations)

Tensor operations:
* add
* subtract
* multiplication
* division
* matrix multiplication

In [23]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [24]:
tensor + 10

tensor([11, 12, 13])

In [25]:
tensor * 10

tensor([10, 20, 30])

In [26]:
tensor - 10

tensor([-9, -8, -7])

In [27]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [28]:
#inbuild pytorch functions
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

2 main ways of performing multiplication in nueral networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product) (obviosly used more often)

In [29]:
# Element-wise multiplication
print(tensor, "*",tensor)
print(f"equals {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals tensor([1, 4, 9])


In [30]:
# Matrix multlication
tensor = torch.rand(7,3)
tensor1 = torch.rand(3,4)
torch.matmul(tensor,tensor1)

tensor([[0.6406, 1.0121, 1.2421, 1.2106],
        [0.3897, 0.4534, 0.6595, 0.6333],
        [0.4898, 0.6961, 0.8790, 0.8779],
        [0.2555, 0.5721, 0.6593, 0.5855],
        [0.5219, 0.8507, 0.9434, 1.0087],
        [0.2259, 0.4465, 0.7376, 0.4668],
        [0.3372, 0.5095, 0.3184, 0.6447]])

In [31]:
#matrix transpose
tensor

tensor([[0.8316, 0.9798, 0.8788],
        [0.1247, 0.7951, 0.7170],
        [0.4481, 0.8606, 0.7254],
        [0.7405, 0.1421, 0.2493],
        [0.7217, 0.8212, 0.5709],
        [0.5543, 0.0741, 0.5482],
        [0.3170, 0.7551, 0.0466]])

In [32]:
tensor.T

tensor([[0.8316, 0.1247, 0.4481, 0.7405, 0.7217, 0.5543, 0.3170],
        [0.9798, 0.7951, 0.8606, 0.1421, 0.8212, 0.0741, 0.7551],
        [0.8788, 0.7170, 0.7254, 0.2493, 0.5709, 0.5482, 0.0466]])

### Finding min,max,mean,sum etc(tensor aggregation)

In [33]:
tensor.max()

tensor(0.9798)

In [34]:
# mean needs the data type to be float32 or some complex sh8 not int
int_t = torch.arange(1,10)
int_t.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [35]:
int_t.type(torch.float32).mean()                                   

tensor(5.)

In [36]:
# positonal max min
int_t.argmin() # returns the index of the min value

tensor(0)

### reshaping viewing and stacking
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (Swapped) in a certain view

In [37]:
#new tensor
x =torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [38]:
#Reshape
x_reshape = x.reshape(3,3)
x_reshape,x_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [39]:
# Change the view
z = x.view(3,3)
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [40]:
# z and x share the same memory but only the view changes hence any changes made on z will reflect on x
z[1][1] = 66
z,x

(tensor([[ 1.,  2.,  3.],
         [ 4., 66.,  6.],
         [ 7.,  8.,  9.]]),
 tensor([ 1.,  2.,  3.,  4., 66.,  6.,  7.,  8.,  9.]))

In [41]:
# Stack tensors on top of each other
x_stacked = torch.stack([x_reshape,x_reshape],dim=1)
x_stacked

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 4., 66.,  6.],
         [ 4., 66.,  6.]],

        [[ 7.,  8.,  9.],
         [ 7.,  8.,  9.]]])

In [42]:
# Squeeze 
tensor=torch.rand(1 ,10)
tensor

tensor([[0.7228, 0.0336, 0.3579, 0.4388, 0.6863, 0.4444, 0.8746, 0.3352, 0.2252,
         0.7120]])

In [43]:
# tensor.squeeze() - removes all the single dimension from a target tensor
print(f"Previous tensor: {tensor}")
print(f"Previous shape: {tensor.shape}")

tensor_squeezed = tensor.squeeze()
print(f"\nNew tensor: {tensor_squeezed}")
print(f"New shape: {tensor_squeezed.shape}")


Previous tensor: tensor([[0.7228, 0.0336, 0.3579, 0.4388, 0.6863, 0.4444, 0.8746, 0.3352, 0.2252,
         0.7120]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([0.7228, 0.0336, 0.3579, 0.4388, 0.6863, 0.4444, 0.8746, 0.3352, 0.2252,
        0.7120])
New shape: torch.Size([10])


In [44]:
# tensor.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Old tensor: {tensor_squeezed}")
print(f"Old shape: {tensor.shape}")

tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=-1)
print(f"\nNew tensor: {tensor_unsqueezed}")
print(f"New shape: {tensor_unsqueezed.shape}")

Old tensor: tensor([0.7228, 0.0336, 0.3579, 0.4388, 0.6863, 0.4444, 0.8746, 0.3352, 0.2252,
        0.7120])
Old shape: torch.Size([1, 10])

New tensor: tensor([[0.7228],
        [0.0336],
        [0.3579],
        [0.4388],
        [0.6863],
        [0.4444],
        [0.8746],
        [0.3352],
        [0.2252],
        [0.7120]])
New shape: torch.Size([10, 1])


In [45]:
# torch.permute - rearranges the dimension of a target tensor in a specific order
original = torch.rand(size = (5,4,3))
print(f"original tensor: {original}")
print(f"original shape: {original.shape}")
original_permute = original.permute(2,0,1)
print(f"\npermuted tensor{original_permute}")
print(f"permuted shape: {original_permute.shape}")

original tensor: tensor([[[0.4600, 0.9246, 0.6049],
         [0.4752, 0.9126, 0.8775],
         [0.3411, 0.8306, 0.6232],
         [0.3697, 0.4355, 0.9945]],

        [[0.6081, 0.3401, 0.6936],
         [0.8883, 0.7630, 0.8623],
         [0.8676, 0.5601, 0.1810],
         [0.6142, 0.9756, 0.5162]],

        [[0.1765, 0.1190, 0.2450],
         [0.2094, 0.6094, 0.8048],
         [0.4720, 0.3989, 0.1036],
         [0.1839, 0.3778, 0.1332]],

        [[0.8564, 0.1715, 0.1873],
         [0.2305, 0.0251, 0.7820],
         [0.3314, 0.1051, 0.4450],
         [0.7271, 0.7876, 0.2769]],

        [[0.5820, 0.6702, 0.6693],
         [0.0224, 0.2586, 0.4640],
         [0.2890, 0.7901, 0.1657],
         [0.9504, 0.4862, 0.8204]]])
original shape: torch.Size([5, 4, 3])

permuted tensortensor([[[0.4600, 0.4752, 0.3411, 0.3697],
         [0.6081, 0.8883, 0.8676, 0.6142],
         [0.1765, 0.2094, 0.4720, 0.1839],
         [0.8564, 0.2305, 0.3314, 0.7271],
         [0.5820, 0.0224, 0.2890, 0.9504]],

  

### Indexing
similar to numpy

In [46]:
tensor = torch.arange(1,10).reshape(1,3,3)
tensor,tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
tensor[0][0]

tensor([1, 2, 3])

In [49]:
tensor[0][0][0]

tensor(1)

In [50]:
# using " : "
# getting all the values of the 0th and 1st dimension but only index 1 of the 2nd dimension
tensor[:,:,1]

tensor([[2, 5, 8]])

In [51]:
tensor[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy to PyTorch tensor -> `torch.from_numpy(ndarray)`
* tensor -> NumPy -> `torch.tensor.numpy()`

In [52]:
# NumPy array to tensor
import numpy as np
arr = np.arange(1,10)
tensor = torch.from_numpy(arr) # same dtype as the arr
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [53]:
#in place operations reflect in both tensor and numpy
arr+=1
tensor,arr

(tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [54]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [55]:

tensor=tensor +1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (making the code less random)

steps involed in how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data->  again -> again -> again`

so as to reduce teh randomness in the neural networks and pytorch we use **random seed**.

Essentially what the random seed does is "flavour" the randomness.


In [56]:
import torch

#Creating 2 random tensors
rand_1 = torch.rand(3,4)
rand_2 = torch.rand(3,4)

print(rand_1)
print(rand_2)
print(rand_1==rand_2)

tensor([[0.4514, 0.3255, 0.5820, 0.4958],
        [0.6796, 0.7735, 0.1865, 0.1349],
        [0.8087, 0.1172, 0.0905, 0.1479]])
tensor([[0.9029, 0.4334, 0.7018, 0.6195],
        [0.3031, 0.2298, 0.8661, 0.2831],
        [0.1126, 0.6651, 0.4717, 0.8678]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [57]:
# making random but reproducible tensors
torch.manual_seed(42)
rand_1 = torch.rand(3,4)

torch.manual_seed(42) # resets the seed
rand_2 = torch.rand(3,4)

print(rand_1)
print(rand_2)
print(rand_1==rand_2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and Pytorch objects on the GPUs


## check for gpu access with pytorch

In [58]:
import torch
print(torch.version.cuda)          # Should show CUDA version like '11.8'
print(torch.cuda.is_available())   # Should be True
print(torch.cuda.current_device()) # Should give a device index, e.g., 0
print(torch.cuda.get_device_name(0))

11.8
True
0
NVIDIA GeForce GTX 1650


In [59]:
# Setup device agnostic code

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [60]:
# By default tensor is created on the cpu
tensor = torch.arange(1,10)
tensor.device # tensor not in gpu

device(type='cpu')

In [61]:
#move tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')

## Moving tensors back to the CPU

In [62]:
# if tensor is on gpu, cant convert it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [63]:
#hence move it to cpu first and then convert it to numpy
tensoroncpu = tensor_on_gpu.to("cpu")
tensoroncpu.numpy()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)